ARG ostype
ARG psversion=7.2.0
ARG version

FROM mcr.microsoft.com/powershell:${psversion}-${ostype}-${version}

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV NEXUS_VERSION "0.16.0"

LABEL maintainer="Jeremie Patigny <jpatigny@gmail.com>"

RUN iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

RUN 

ADD ./config/windows_exporter.yml C:/windows-exporter/config/windows_exporter.yml

USER       ContainerUser
WORKDIR    C:/windows-exporter-data
EXPOSE     9182
VOLUME     [ "C:/windows-exporter-data" ]
ENTRYPOINT [ "C:/windows-exporter/windows_exporter.exe" ]
CMD        [ "--config.file=C:/windows-exporter/config/windows_exporter.yml" ]