FROM chocolatey/choco:latest-windows

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV VERSION "3.38.0.01"



RUN choco install -y pwsh ; \
    choco install -y nexus-repository--version $env:version

RUN 

ADD ./config/windows_exporter.yml C:/windows-exporter/config/windows_exporter.yml

USER       ContainerUser
WORKDIR    C:/windows-exporter-data
EXPOSE     9182
VOLUME     [ "C:/windows-exporter-data" ]
ENTRYPOINT [ "C:/windows-exporter/windows_exporter.exe" ]
CMD        [ "--config.file=C:/windows-exporter/config/windows_exporter.yml" ]