ARG OS_TYPE
ARG OS_VERSION

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build

ARG VERSION=2.6.0

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

USER ContainerAdministrator
RUN md C:\loki\config,C:\loki\data,C:\loki\tmp ; \
    Invoke-Webrequest -uri https://github.com/grafana/loki/releases/download/v$($env:VERSION)/loki-windows-amd64.exe.zip -OutFile loki.zip -Verbose ; \
    Expand-Archive -Path loki.zip -DestinationPath C:\loki -Verbose

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION}

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

COPY --from=build C:/loki C:/loki
ADD ./config/loki-local-config.yaml C:/loki/config/loki-local-config.yaml

USER       ContainerUser
WORKDIR    C:/loki
ENTRYPOINT [ "loki-windows-amd64.exe" ]
CMD        [ "--config.file=C:/loki/config/loki-local-config.yaml" ]
