ARG OS_TYPE
ARG OS_VERSION

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build

ARG VERSION=0.24.0

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

LABEL "maintainer"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.authors"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.vendor"="Jeremie Patigny"
LABEL "org.opencontainers.image.url"="https://github.com/jpatigny/dockerfiles/alertmanager"
LABEL "org.opencontainers.image.documentation"="https://github.com/jpatigny/dockerfiles/tree/main/alertmanager"
LABEL "org.opencontainers.image.source"="https://github.com/jpatigny/dockerfiles/tree/main/alertmanager"
LABEL "org.opencontainers.image.ref.name"="AlertManager ${VERSION}"
LABEL "org.opencontainers.image.title"="AlertManager ${VERSION}"
LABEL "org.opencontainers.image.description"="AlertManager ${VERSION}"

RUN md C:\temp ; \
    Invoke-Webrequest -uri https://github.com/prometheus/alertmanager/releases/download/v$($env:VERSION)/alertmanager-$($env:VERSION).windows-amd64.zip -outfile C:\temp\alertmanager-$($env:VERSION).windows-amd64.zip ; \
    Expand-Archive -Path C:\temp\alertmanager-$($env:VERSION).windows-amd64.zip -DestinationPath C:\temp ; \
    mv C:\temp\alertmanager-$($env:VERSION).windows-amd64 C:\temp\alertmanager ; \
    md C:\temp\alertmanager\config ; \
    mv C:\temp\alertmanager\alertmanager.yml C:\temp\alertmanager\config\alertmanager.yml

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION}

RUN md c:\alertmanager-data

COPY --from=build C:/temp/alertmanager C:/alertmanager

USER       ContainerUser
WORKDIR    C:/alertmanager-data
EXPOSE     9093
VOLUME     [ "C:/alertmanager-data" ]
ENTRYPOINT [ "C:/alertmanager/alertmanager.exe" ]
CMD        [ "--config.file=C:/alertmanager/config/alertmanager.yml" ]

