ARG OS_TYPE="nanoserver"
ARG OS_VERSION="20h2"

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG VERSION=0.24.0

RUN md C:\temp ; \
    Invoke-Webrequest -uri https://github.com/prometheus/alertmanager/releases/download/v$($env:VERSION)/alertmanager-$($env:VERSION).windows-amd64.zip -outfile am.zip ; \
    Expand-Archive -Path am.zip -DestinationPath C:\temp ; \
    mv C:\temp\alertmanager-$($env:VERSION).windows-amd64 C:\temp\alertmanager ; \
    md C:\temp\alertmanager\bin,C:\temp\alertmanager\conf,C:\temp\alertmanager\data ; \
    mv C:\temp\alertmanager\alertmanager.yml C:\temp\alertmanager\conf\alertmanager.yml ; \
    mv C:\temp\alertmanager\alertmanager.exe C:\temp\alertmanager\bin\alertmanager.exe

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION}

COPY --from=build C:/temp/alertmanager C:/alertmanager

USER       ContainerUser
WORKDIR    C:/alertmanager
EXPOSE     9093
VOLUME     [ "C:/alertmanager/data" ]
ENTRYPOINT [ "C:/alertmanager/bin/alertmanager.exe" ]
CMD        [ "--config.file=C:/alertmanager/conf/alertmanager.yml" ]

