ARG ${BASE}

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-${BASE}
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

ARG PUPPET_AGENT_VERSION="6.28.0"
ARG PDK_VERSION="2.4.0.1"
ARG RUBY_VERSION="3.1.3.1"

RUN Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -value 1 ; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')) ; \
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

RUN Install-Module PowerShellGet -Force -AllowClobber ; \
    Install-Module Pester -Scope AllUsers -SkipPublisherCheck -Force ; \
    choco feature disable -n=showDownloadProgress ; \
    choco install -y powershell-core ; \
    choco install -y git ; \
    choco install -y puppet-agent --version $env:PUPPET_AGENT_VERSION ; \
    choco install -y pdk --version $env:PDK_VERSION ; \
    choco install -y ruby -version $env:RUBY_VERSION ; \
    rm $env:temp\* -Force -Recurse

RUN gem install specific_install ; \
    gem specific_install https://github.com/ahmet2mir/librarian-puppet.git

RUN [System.Environment]::SetEnvironmentVariable('PDK_DISABLE_ANALYTICS', 'true', [EnvironmentVariableTarget]::Machine)

WORKDIR C:/puppet
CMD [ "pwsh.exe" ]