ARG BASE

FROM mcr.microsoft.com/windows/servercore:${BASE}

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

ARG PUPPET_AGENT_VERSION=8.6.0
# ARG PDK_VERSION=3.2.0.1

COPY ./puppet/data/ C:/data

USER ContainerAdministrator
RUN Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1 ; \
    Invoke-RestMethod -Uri 'https://get.scoop.sh' -OutFile 'install.ps1' ; \
    .\install.ps1 -RunAsAdmin ; \
    scoop install C:/data/puppet-agent.json --global ; \
    scoop install ruby --global ; \
    scoop install pwsh --global ; \
    scoop install git --global ; \
    psmodule

# USER ContainerAdministrator
# RUN msiexec /qn /norestart /i https://downloads.puppetlabs.com/windows/puppet8/pdk-$($env:PDK_VERSION)-x64.msi && \
#     Write-Host 'pdk installed'

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

# Install the Pester PowerShell module
RUN Set-PSResourceRepository -Name PSGallery -Trusted ; \
    Install-PSResource -Name Pester -Scope CurrentUser ; \
    Write-Host "Installing Librarian..." ; \
    gem install librarian-puppet -v 5.0.0 ; \
    [System.Environment]::SetEnvironmentVariable('PDK_DISABLE_ANALYTICS', 'true', [EnvironmentVariableTarget]::Machine) ; \
    Remove-Item -Path "$env:TEMP\*" -Force -Recurse ; \
    Remove-Item -Path 'C:\Windows\temp\*' -Force -Recurse ; \
    Remove-Item -Path 'C:/*.json' -Force

# Set the working directory
WORKDIR C:/puppet

# Set the default command to PowerShell Core
CMD [ "pwsh.exe" ]