ARG OS_TYPE="nanoserver"
ARG OS_VERSION="20h2"

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG VERSION=0.2.3

RUN iwr -uri https://github.com/hashicorp/http-echo/releases/download/v$($env:VERSION)/http-echo_$($env:VERSION)_windows_amd64.zip -OutFile C:\Windows\temp\http.zip -Verbose ; \
    Expand-Archive -Path C:\Windows\temp\http.zip -DestinationPath C:\ -Verbose ; \
    mv C:\http-echo C:\http-echo.exe ; \
    Remove-Item C:\Windows\temp\http.zip -Force 

USER       ContainerUser
ENTRYPOINT [ "C:/http-echo.exe" ]