ARG OS_TYPE
ARG OS_VERSION

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build

ARG VERSION=0.21.1

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN md C:\temp ; \
    Invoke-Webrequest -uri https://github.com/prometheus/blackbox_exporter/releases/download/v$($env:VERSION)/blackbox_exporter-$($env:VERSION).windows-amd64.zip -outfile C:\temp\blackbox_exporter-$($env:VERSION).windows-amd64.zip -Verbose ; \
    Expand-Archive -Path C:\temp\blackbox_exporter-$($env:VERSION).windows-amd64.zip -DestinationPath C:\temp -Verbose ; \
    mv C:\temp\blackbox_exporter-$($env:VERSION).windows-amd64 C:\temp\blackbox_exporter -Verbose ; \
    md C:\temp\blackbox_exporter\config ; \
    mv C:\temp\blackbox_exporter\blackbox.yml C:\temp\blackbox_exporter\config

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION}

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

LABEL "maintainer"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.authors"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.vendor"="Jeremie Patigny"
LABEL "org.opencontainers.image.url"="https://github.com/jpatigny/dockerfiles/blackbox_exporter"
LABEL "org.opencontainers.image.documentation"="https://github.com/jpatigny/dockerfiles/tree/main/blackbox_exporter"
LABEL "org.opencontainers.image.source"="https://github.com/jpatigny/dockerfiles/tree/main/blackbox_exporter"
LABEL "org.opencontainers.image.ref.name"="blackbox_exporter ${VERSION}"
LABEL "org.opencontainers.image.title"="blackbox_exporter ${VERSION}"
LABEL "org.opencontainers.image.description"="blackbox_exporter ${VERSION}"

RUN md C:\blackbox_exporter-data

COPY --from=build C:/temp/blackbox_exporter C:/blackbox_exporter

USER       ContainerUser
WORKDIR    C:/blackbox_exporter-data
EXPOSE     9115
VOLUME     [ "C:/blackbox_exporter-data" ]
ENTRYPOINT [ "C:/blackbox_exporter/blackbox_exporter.exe" ]
CMD        [ "--config.file=C:/blackbox_exporter/config/blackbox.yml" ]
