ARG OS_TYPE="windowsservercore"
ARG OS_VERSION="20h2"

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG VERSION=8.4.7

USER ContainerAdministrator
RUN Invoke-Webrequest -uri https://dl.grafana.com/enterprise/release/grafana-enterprise-$($env:VERSION).windows-amd64.zip -outfile grafana.zip ; \
    Expand-Archive -Path grafana.zip -DestinationPath C:\ ; \
    mv C:\grafana* C:\grafana ; \
    mv C:\grafana\conf\sample.ini C:\grafana\conf\custom.ini ; \
    (gc C:\grafana\conf\custom.ini) -replace ';http_port','http_port' | Set-Content C:\grafana\conf\custom.ini

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION}

COPY --from=build C:/grafana C:/grafana

USER       ContainerAdministrator
WORKDIR    C:/grafana
EXPOSE     3000
ENTRYPOINT [ "C:/grafana/bin/grafana-server.exe" ]
