ARG OS_TYPE
ARG OS_VERSION

FROM python:${OS_TYPE}-${OS_VERSION}

ARG VERSION=2.0.1222

LABEL "maintainer"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.authors"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.vendor"="Jeremie Patigny"
LABEL "org.opencontainers.image.url"="https://github.com/jpatigny/dockerfiles/checkov"
LABEL "org.opencontainers.image.documentation"="https://github.com/jpatigny/dockerfiles/tree/main/checkov"
LABEL "org.opencontainers.image.source"="https://github.com/jpatigny/dockerfiles/tree/main/checkov"
LABEL "org.opencontainers.image.ref.name"="checkov ${VERSION}"
LABEL "org.opencontainers.image.title"="checkov ${VERSION}"
LABEL "org.opencontainers.image.description"="checkov ${VERSION}"

RUN python.exe -m pip install --upgrade pip ; \
    pip3 install --upgrade setuptools ; \
    pip3 install checkov==${env:VERSION}

ENTRYPOINT [ "powershell.exe" ]
CMD [ "checkov","--help" ]
