ARG OS_TYPE="windowsservercore"
ARG OS_VERSION="20h2"

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION}
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV VERSION "0.19.0"

RUN md C:\windows-exporter ; \
    Invoke-Webrequest -uri https://github.com/prometheus-community/windows_exporter/releases/download/v$($env:VERSION)/windows_exporter-$($env:VERSION)-amd64.exe -outfile C:\windows-exporter\windows_exporter.exe -Verbose

USER       ContainerUser
EXPOSE     9182
ENTRYPOINT [ "C:/windows-exporter/windows_exporter.exe" ]