FROM mcr.microsoft.com/powershell:7.2.0-windowsservercore-1809 as build

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV WINDOWS_EXPORTER_VERSION "0.16.0"

LABEL maintainer="Jeremie Patigny <jpatigny@gmail.com>"

RUN md C:\windows-exporter-data ; \
    md C:\windows-exporter\config ; \
    Invoke-Webrequest -uri https://github.com/prometheus-community/windows_exporter/releases/download/v$($env:WINDOWS_EXPORTER_VERSION)/windows_exporter-$($env:WINDOWS_EXPORTER_VERSION)-amd64.exe -outfile C:\windows-exporter\windows_exporter.exe -Verbose

ADD ./config/windows_exporter.yml C:/windows-exporter/config/windows_exporter.yml

USER       ContainerUser
WORKDIR    C:/windows-exporter-data
EXPOSE     9182
VOLUME     [ "C:/windows-exporter-data" ]
ENTRYPOINT [ "C:/windows-exporter/windows_exporter.exe" ]
CMD        [ "--config.file=C:/windows-exporter/config/windows_exporter.yml" ]