ARG OS_TYPE="windowsservercore"
ARG OS_VERSION="20h2"

FROM mcr.microsoft.com/powershell:${OS_TYPE}-${OS_VERSION} as build

ARG VERSION=1.20.2

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-Webrequest -uri http://nginx.org/download/nginx-$($env:version).zip -OutFile nginx.zip -Verbose ; \
    Expand-Archive nginx.zip -DestinationPath C:\ -Verbose ; \
    rm nginx.zip -Force ; \
    mv C:\nginx* C:\nginx ; \
    New-Item -type directory "C:\nginx\enabled-sites\html"
    

ADD ./data/index.html C:/nginx/enabled-sites/html
ADD ./data/nginx.conf C:/nginx/conf/nginx.conf

WORKDIR C:/nginx
EXPOSE 80
CMD ["nginx","-g","daemon off;"]