FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV chocolateyVersion 0.10.15
ENV chocolateyUseWindowsCompression false

RUN mkdir $env:ProgramFiles\WindowsPowerShell\Modules\ChocoHelpers ; \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress

ADD ["data/ChocoHelpers.psm1", "C:/Program Files/WindowsPowerShell/Modules/ChocoHelpers"]

ENTRYPOINT [ "powershell.exe" ]