ARG version

FROM mcr.microsoft.com/windows/servercore:${version}

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV CHOCO_VERSION "0.11.3"
ENV chocolateyUseWindowsCompression false

LABEL "maintainer"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.authors"="Jeremie Patigny <jpatigny@gmail.com>"
LABEL "org.opencontainers.image.vendor"="Jeremie Patigny"
LABEL "org.opencontainers.image.url"="https://github.com/jpatigny/dockerfiles/chocolatey"
LABEL "org.opencontainers.image.documentation"="https://github.com/jpatigny/dockerfiles/tree/main/chocolatey"
LABEL "org.opencontainers.image.source"="https://github.com/jpatigny/dockerfiles/tree/main/chocolatey"
LABEL "org.opencontainers.image.ref.name"="chocolatey ${CHOCO_VERSION}"
LABEL "org.opencontainers.image.title"="chocolatey ${CHOCO_VERSION}"
LABEL "org.opencontainers.image.description"="chocolatey ${CHOCO_VERSION}"

RUN mkdir $env:ProgramFiles\WindowsPowerShell\Modules\ChocoHelpers ; \
    $env:chocolateyVersion = $env:CHOCO_VERSION ; \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress

ADD ["data/ChocoHelpers.psm1", "C:/Program Files/WindowsPowerShell/Modules/ChocoHelpers"]

ENTRYPOINT [ "powershell.exe" ]